# Generated by Django 3.2 on 2022-11-20 04:42

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_date', account.models.AutoNewDateTimeField(db_index=True, editable=False)),
                ('follow_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans', to='account.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='account.member')),
            ],
        ),
    ]
